version: '3'


services:
  nuxt:
    # change container name depending on project name
    container_name: ${APP_NAME}
    ports:
      # change external port deneding on server side requirements
      - ${APP_PORT}:3000
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
